library(testthat)

source(file.path("functions", "audit_logger.R"))
source(file.path("functions", "clean_data.R"))
source(file.path("functions", "import_github_data_raw.R"))
source(file.path("functions", "load_append_redcap_mapping.R"))
source(file.path("functions", "load_redcap_config.R"))
source(file.path("functions", "keyring_setup_helpers.R"))
source(file.path("functions", "normalize_mapping_terms.R"))
source(file.path("functions", "prepare_append_trial.R"))
source(file.path("functions", "map_redcap.R"))
source(file.path("functions", "parse_ast_chart_report_full.R"))
source(file.path("functions", "read_pdf_manifest.R"))
source(file.path("functions", "read_vitek_pdf_full.R"))
source(file.path("functions", "read_redcap_dictionary.R"))
source(file.path("functions", "run_shiny_pipeline.R"))
source(file.path("functions", "suggest_redcap_target_fields.R"))
source(file.path("functions", "update_append_mapping_targets.R"))
source(file.path("functions", "validate_redcap_data.R"))
source(file.path("functions", "upload_redcap.R"))
source(file.path("functions", "upload_dispatcher.R"))

test_dir("tests/testthat")
